language: android
jdk: oraclejdk7
sudo: true

os:
  - linux

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25

script:
  - ./gradlew clean check --profile
